image: tossp/lede:latest

before_script:
  - wget -O /etc/apt/sources.list http://mirrors.163.com/.help/sources.list.trusty
  - apt-get -qqy update

stages:
  - 测试阶段
  - 构建阶段
  - 部署阶段
     
构建编译:
  stage: 构建阶段
  retry: 2
  artifacts:
    name: "${CI_JOB_STAGE}_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    expire_in: 6 mos
    paths:
      - bin/
  script:  
    - apt-get -qqy install sudo bsdmainutils autoconf automake libtool
    - mkdir -p /cache/$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG/{dl,feeds,build_dir,staging_dir} 
    - chown -R lede /cache/$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
    - ln -s /cache/$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG/dl dl
    - ln -s /cache/$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG/feeds feeds
    - ln -s /cache/$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG/build_dir build_dir
    - ln -s /cache/$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG/staging_dir staging_dir
    - ./scripts/feeds update -a 
    - ./scripts/feeds install -a
    - cp tsconfig .config
    - make defconfig
    - chown -R lede ../
    - chown -R lede $HOME
    - chmod -R u+w ../
    - sudo -u lede make -j1 V=1
  only:
    - ci
     
七牛发布:
  stage: 部署阶段
  dependencies:
    - 构建编译
  environment:
    name: 'QN-OSS'
    url: http://lede-k3.test.tossp.com
  variables:
    TS_QN_BUCKET: 'lede-k3'
  script:
    - apt-get -qqy install tree
    - echo \<pre\> > bin/index.html
    - echo 生成时间：$(date '+%Y-%m-%d %H:%M:%S') >> bin/index.html
    - echo >> bin/index.html
    - echo 快捷地址 >> bin/index.html
    - echo /targets/bcm53xx/generic/lede-bcm53xx-phicomm-k3-squashfs.trx >> bin/index.html
    - echo /targets/bcm53xx/generic/sha256sums >> bin/index.html
    - echo /targets/bcm53xx/generic/config.seed >> bin/index.html
    - echo >> bin/index.html
    - echo 目录结构 >> bin/index.html
    - tree -L 5 bin >> bin/index.html
    - echo \</pre\> >> bin/index.html
    - wget -O /bin/qshell http://devtools.qiniu.com/2.1.5/qshell-linux-x64
    - chmod a+x /bin/qshell
    - qshell account $QNAK $QNSK
    - qshell qupload2 -log-file /root/ts.log -check-exists -check-hash -check-size -overwrite -rescan-local -thread-count 6 -src-dir bin -bucket $TS_QN_BUCKET
    - cat /root/ts.log
  only:
    - ci
    